version: "3"
services:
  abc:
    build:
      context: .
      target: dev
    volumes:
      - .:/abc:rw
    ports:
      - "3000:3000"
    # depends_on:
    #   - db

  # db:
  #   image: mysql:5.7.22
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "root"
  #     MYSQL_DATABASE: "todo"
  #     MYSQL_USER: "user"
  #     MYSQL_PASSWORD: "root"
    
  #   volumes:
  #     - .docker/db_data:/var/lib/mysql
  #   ports:
  #     - "33078:3306"

    



  